# Generated by Django 4.0.2 on 2022-02-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panelmember',
            old_name='name',
            new_name='member_name',
        ),
    ]
