# Generated by Django 4.0.2 on 2022-02-13 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_name_panelmember_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantdetail',
            name='slot_booked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.interviewslot'),
        ),
    ]
