# Generated by Django 4.0.2 on 2022-07-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_participantdetail_slot_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewslot',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
